[package]
name = "scon"
version = "0.1.0"
edition = "2021"
description = "Stateful Containers CLI tool"
authors = ["Art Fewell <afewell@gmail.com>"]

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"